//! Keyboard input handling for Wayland compositor.

use smithay::backend::input::{InputBackend, KeyboardKeyEvent};
use smithay::input::keyboard::{FilterResult, KeyboardHandle};
use smithay::wayland::input_method::InputMethodSeat;

use crate::backend::wayland::compositor::layer_shell::LayerKeyboardPolicy;
use crate::backend::wayland::compositor::{KeyboardFocusTarget, WaylandState};
use crate::backend::wayland::input::modifiers_to_x11_mask;
use crate::wm::Wm;

use smithay::utils::SERIAL_COUNTER;

/// Detect if a key event corresponds to a VT switch (Ctrl+Alt+F1..F12 or XF86Switch_VT_1..12).
pub fn vt_switch_target(
    raw_keysym: u32,
    modifiers: &smithay::input::keyboard::ModifiersState,
) -> Option<i32> {
    use crate::config::keysyms::*;

    // Direct XF86Switch_VT_1..12 keysyms (generated by some XKB layouts)
    if (XF86XK_SWITCH_VT_1..=XF86XK_SWITCH_VT_12).contains(&raw_keysym) {
        return Some((raw_keysym - XF86XK_SWITCH_VT_1 + 1) as i32);
    }

    // Standard Ctrl + Alt + F1..F12
    if modifiers.ctrl && modifiers.alt && (XK_F1..=XK_F12).contains(&raw_keysym) {
        return Some((raw_keysym - XK_F1 + 1) as i32);
    }

    None
}

/// Handle keyboard events.
pub fn handle_keyboard<B: InputBackend>(
    wm: &mut Wm,
    state: &mut WaylandState,
    keyboard_handle: &KeyboardHandle<WaylandState>,
    event: impl KeyboardKeyEvent<B>,
) {
    let serial = SERIAL_COUNTER.next_serial();
    // When the session is locked, all input must go to the lock surface.
    let mut wm_shortcuts_allowed = if state.is_locked() {
        false
    } else {
        match keyboard_handle.current_focus() {
            None => true,
            Some(KeyboardFocusTarget::Window(ref w)) => {
                // Use the unified window classifier to determine if shortcuts
                // should be suppressed. This handles all overlay types consistently.
                !state.should_suppress_shortcuts_for(w)
            }
            // Layer shell surfaces (e.g. rofi, dmenu) that request exclusive keyboard
            // interactivity must receive all input — suppress WM shortcuts for them.
            // Non-exclusive surfaces (e.g. the bar) still allow WM shortcuts.
            Some(KeyboardFocusTarget::WlSurface(ref surface)) => !state
                .layer_keyboard_policy(surface)
                .is_some_and(LayerKeyboardPolicy::suppresses_wm_shortcuts),
            Some(KeyboardFocusTarget::Popup(_)) => false,
        }
    };
    let key_code = event.key_code();
    let key_state = event.state();
    keyboard_handle.input(
        state,
        key_code,
        key_state,
        serial,
        event.time_msec(),
        |data, modifiers, keysym| {
            if key_state == smithay::backend::input::KeyState::Released {
                if data.runtime.intercepted_key_releases.remove(&key_code) {
                    return FilterResult::Intercept(());
                }
                return FilterResult::Forward;
            }
            let raw_keysym = keysym.raw_syms().first().map_or(0, |ks| ks.raw());

            // Emergency VT switching (Ctrl+Alt+F1..F12 or XF86Switch_VT_1..12)
            // This is processed unconditionally before window grabs and shortcut suppression.
            if let Some(vt) = vt_switch_target(raw_keysym, modifiers) {
                if data.switch_vt(vt) {
                    data.runtime.intercepted_key_releases.insert(key_code);
                    return FilterResult::Intercept(());
                }
            }

            if raw_keysym == crate::config::keysyms::XK_ESCAPE {
                let closed_native = data.dismiss_native_systray_menu();
                let closed_hosted = crate::backend::wayland::input::bar::close_systray_menu(wm);
                if closed_hosted {
                    data.request_bar_redraw();
                }
                if closed_native || closed_hosted {
                    data.runtime.intercepted_key_releases.insert(key_code);
                    return FilterResult::Intercept(());
                }
            }
            if wm_shortcuts_allowed {
                let mod_mask = modifiers_to_x11_mask(modifiers);
                let ctx = wm.ctx();
                let crate::contexts::WmCtx::Wayland(ctx) = ctx else {
                    return FilterResult::Forward;
                };
                let mut wm_ctx = crate::contexts::WmCtx::Wayland(ctx);
                if crate::keyboard::handle_keysym(&mut wm_ctx, raw_keysym, mod_mask) {
                    data.runtime.intercepted_key_releases.insert(key_code);
                    return FilterResult::Intercept(());
                }
            }
            FilterResult::Forward
        },
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::keysyms::*;
    use smithay::input::keyboard::ModifiersState;

    #[test]
    fn test_vt_switch_direct_keysyms() {
        let empty_mods = ModifiersState::default();
        assert_eq!(vt_switch_target(XF86XK_SWITCH_VT_1, &empty_mods), Some(1));
        assert_eq!(vt_switch_target(XF86XK_SWITCH_VT_3, &empty_mods), Some(3));
        assert_eq!(vt_switch_target(XF86XK_SWITCH_VT_7, &empty_mods), Some(7));
        assert_eq!(vt_switch_target(XF86XK_SWITCH_VT_12, &empty_mods), Some(12));
    }

    #[test]
    fn test_vt_switch_ctrl_alt_function_keys() {
        let mut mods = ModifiersState::default();
        mods.ctrl = true;
        mods.alt = true;

        assert_eq!(vt_switch_target(XK_F1, &mods), Some(1));
        assert_eq!(vt_switch_target(XK_F2, &mods), Some(2));
        assert_eq!(vt_switch_target(XK_F3, &mods), Some(3));
        assert_eq!(vt_switch_target(XK_F7, &mods), Some(7));
        assert_eq!(vt_switch_target(XK_F12, &mods), Some(12));

        // Missing ctrl
        let mut no_ctrl = ModifiersState::default();
        no_ctrl.alt = true;
        assert_eq!(vt_switch_target(XK_F3, &no_ctrl), None);

        // Missing alt
        let mut no_alt = ModifiersState::default();
        no_alt.ctrl = true;
        assert_eq!(vt_switch_target(XK_F3, &no_alt), None);

        // Different key
        assert_eq!(vt_switch_target(XK_ESCAPE, &mods), None);
        assert_eq!(vt_switch_target(XK_A, &mods), None);
    }
}
