//! Keyboard input handling for Wayland compositor.

pub(crate) mod recovery;

use smithay::backend::input::{InputBackend, KeyboardKeyEvent};
use smithay::input::keyboard::{FilterResult, KeyboardHandle};
use smithay::wayland::input_method::InputMethodSeat;
use smithay::wayland::keyboard_shortcuts_inhibit::KeyboardShortcutsInhibitorSeat;
use smithay::wayland::seat::WaylandFocus;

use crate::backend::wayland::compositor::layer_shell::LayerKeyboardPolicy;
use crate::backend::wayland::compositor::{KeyboardFocusTarget, WaylandState};
use crate::backend::wayland::input::modifiers_to_x11_mask;
use crate::wm::Wm;

use smithay::utils::SERIAL_COUNTER;

fn is_shortcut_recovery_chord(
    raw_keysym: u32,
    modifiers: &smithay::input::keyboard::ModifiersState,
) -> bool {
    raw_keysym == crate::config::keysyms::XK_ESCAPE
        && modifiers.logo
        && modifiers.shift
        && !modifiers.ctrl
        && !modifiers.alt
}

/// Why ordinary WM keybindings are withheld for the current key event.
///
/// Emergency VT switching and dismissal of an open compositor-owned menu are
/// handled separately before ordinary keybinding dispatch.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ShortcutSuppression {
    SessionLocked,
    /// A Smithay grab other than the compositor's input-method grab.
    KeyboardGrab,
    /// An active inhibitor whose associated surface currently has focus.
    SurfaceInhibitor,
    ExclusiveLayer,
}

/// Protocol and focus facts used to derive shortcut policy in one place.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
struct ShortcutContext {
    session_locked: bool,
    keyboard_grabbed: bool,
    input_method_grabbed: bool,
    focused_surface_inhibited: bool,
    exclusive_layer: bool,
}

fn select_shortcut_suppression(context: ShortcutContext) -> Option<ShortcutSuppression> {
    if context.session_locked {
        Some(ShortcutSuppression::SessionLocked)
    } else if context.keyboard_grabbed && !context.input_method_grabbed {
        Some(ShortcutSuppression::KeyboardGrab)
    } else if context.focused_surface_inhibited {
        Some(ShortcutSuppression::SurfaceInhibitor)
    } else if context.exclusive_layer {
        Some(ShortcutSuppression::ExclusiveLayer)
    } else {
        None
    }
}

fn shortcut_suppression(
    state: &WaylandState,
    keyboard: &KeyboardHandle<WaylandState>,
) -> Option<ShortcutSuppression> {
    let focus = keyboard.current_focus();
    let focused_surface_inhibited = focus
        .as_ref()
        .and_then(WaylandFocus::wl_surface)
        .and_then(|surface| {
            state
                .seat
                .keyboard_shortcuts_inhibitor_for_surface(surface.as_ref())
        })
        .is_some_and(|inhibitor| inhibitor.is_active());
    let exclusive_layer = focus.as_ref().is_some_and(|focus| {
        let KeyboardFocusTarget::WlSurface(surface) = focus else {
            return false;
        };
        state
            .layer_keyboard_policy(surface)
            .is_some_and(LayerKeyboardPolicy::suppresses_wm_shortcuts)
    });
    select_shortcut_suppression(ShortcutContext {
        session_locked: state.is_locked(),
        keyboard_grabbed: keyboard.is_grabbed(),
        input_method_grabbed: state.seat.input_method().keyboard_grabbed(),
        focused_surface_inhibited,
        exclusive_layer,
    })
}

/// Detect if a key event corresponds to a VT switch (Ctrl+Alt+F1..F12 or XF86Switch_VT_1..12).
pub fn vt_switch_target(
    raw_keysym: u32,
    modifiers: &smithay::input::keyboard::ModifiersState,
) -> Option<i32> {
    use crate::config::keysyms::*;

    // Direct XF86Switch_VT_1..12 keysyms (generated by some XKB layouts)
    if (XF86XK_SWITCH_VT_1..=XF86XK_SWITCH_VT_12).contains(&raw_keysym) {
        return Some((raw_keysym - XF86XK_SWITCH_VT_1 + 1) as i32);
    }

    // Standard Ctrl + Alt + F1..F12
    if modifiers.ctrl && modifiers.alt && (XK_F1..=XK_F12).contains(&raw_keysym) {
        return Some((raw_keysym - XK_F1 + 1) as i32);
    }

    None
}

/// Handle keyboard events.
pub fn handle_keyboard<B: InputBackend>(
    wm: &mut Wm,
    state: &mut WaylandState,
    keyboard_handle: &KeyboardHandle<WaylandState>,
    event: impl KeyboardKeyEvent<B>,
) {
    let serial = SERIAL_COUNTER.next_serial();
    let suppression = shortcut_suppression(state, keyboard_handle);
    let key_code = event.key_code();
    let key_state = event.state();
    keyboard_handle.input(
        state,
        key_code,
        key_state,
        serial,
        event.time_msec(),
        |data, modifiers, keysym| {
            if key_state == smithay::backend::input::KeyState::Released {
                if data.release_shortcut_recovery_key(key_code) {
                    data.runtime.intercepted_key_releases.remove(&key_code);
                    return FilterResult::Intercept(());
                }
                if data.shortcut_recovery_is_armed() && (!modifiers.logo || !modifiers.shift) {
                    data.cancel_shortcut_recovery();
                }
                if data.runtime.intercepted_key_releases.remove(&key_code) {
                    return FilterResult::Intercept(());
                }
                return FilterResult::Forward;
            }
            let raw_keysym = keysym.raw_syms().first().map_or(0, |ks| ks.raw());

            // Key-repeat events remain compositor-owned after recovery has
            // completed, until the matching physical release arrives.
            if data.shortcut_recovery_owns_key(key_code) {
                return FilterResult::Intercept(());
            }

            // Any additional press changes the deliberate recovery chord.
            // Cancel the gesture, then route that extra key normally.
            if data.shortcut_recovery_is_armed() {
                data.cancel_shortcut_recovery();
            }

            if matches!(
                suppression,
                Some(ShortcutSuppression::KeyboardGrab | ShortcutSuppression::SurfaceInhibitor)
            ) && is_shortcut_recovery_chord(raw_keysym, modifiers)
                && let Some(surface) = keyboard_handle
                    .current_focus()
                    .and_then(|focus| focus.wl_surface().map(|surface| surface.into_owned()))
            {
                data.arm_shortcut_recovery(key_code, surface);
                data.runtime.intercepted_key_releases.insert(key_code);
                return FilterResult::Intercept(());
            }

            // Emergency VT switching (Ctrl+Alt+F1..F12 or XF86Switch_VT_1..12)
            // This is processed unconditionally before window grabs and shortcut suppression.
            if let Some(vt) = vt_switch_target(raw_keysym, modifiers)
                && data.switch_vt(vt)
            {
                data.runtime.intercepted_key_releases.insert(key_code);
                return FilterResult::Intercept(());
            }

            if raw_keysym == crate::config::keysyms::XK_ESCAPE {
                let closed_native = data.dismiss_native_systray_menu();
                let closed_hosted = crate::backend::wayland::input::bar::close_systray_menu(wm);
                if closed_hosted {
                    data.request_bar_redraw();
                }
                if closed_native || closed_hosted {
                    data.runtime.intercepted_key_releases.insert(key_code);
                    return FilterResult::Intercept(());
                }
            }
            if suppression.is_none() {
                let mod_mask = modifiers_to_x11_mask(modifiers);
                let ctx = wm.ctx();
                let crate::contexts::WmCtx::Wayland(ctx) = ctx else {
                    return FilterResult::Forward;
                };
                let mut wm_ctx = crate::contexts::WmCtx::Wayland(ctx);
                if crate::keyboard::handle_keysym(&mut wm_ctx, raw_keysym, mod_mask) {
                    data.runtime.intercepted_key_releases.insert(key_code);
                    return FilterResult::Intercept(());
                }
            }
            FilterResult::Forward
        },
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::keysyms::*;
    use smithay::input::keyboard::ModifiersState;

    #[test]
    fn shortcut_suppression_requires_an_explicit_input_policy() {
        assert_eq!(
            select_shortcut_suppression(ShortcutContext::default()),
            None
        );
        assert_eq!(
            select_shortcut_suppression(ShortcutContext {
                exclusive_layer: true,
                ..ShortcutContext::default()
            }),
            Some(ShortcutSuppression::ExclusiveLayer)
        );
        assert_eq!(
            select_shortcut_suppression(ShortcutContext {
                focused_surface_inhibited: true,
                ..ShortcutContext::default()
            }),
            Some(ShortcutSuppression::SurfaceInhibitor)
        );
        assert_eq!(
            select_shortcut_suppression(ShortcutContext {
                keyboard_grabbed: true,
                ..ShortcutContext::default()
            }),
            Some(ShortcutSuppression::KeyboardGrab)
        );
        assert_eq!(
            select_shortcut_suppression(ShortcutContext {
                session_locked: true,
                ..ShortcutContext::default()
            }),
            Some(ShortcutSuppression::SessionLocked)
        );
    }

    #[test]
    fn input_method_grab_alone_keeps_compositor_shortcuts_available() {
        assert_eq!(
            select_shortcut_suppression(ShortcutContext {
                keyboard_grabbed: true,
                input_method_grabbed: true,
                ..ShortcutContext::default()
            }),
            None
        );
    }

    #[test]
    fn security_and_protocol_reasons_have_stable_precedence() {
        assert_eq!(
            select_shortcut_suppression(ShortcutContext {
                session_locked: true,
                keyboard_grabbed: true,
                input_method_grabbed: true,
                focused_surface_inhibited: true,
                exclusive_layer: true,
            }),
            Some(ShortcutSuppression::SessionLocked)
        );
        assert_eq!(
            select_shortcut_suppression(ShortcutContext {
                keyboard_grabbed: true,
                focused_surface_inhibited: true,
                exclusive_layer: true,
                ..ShortcutContext::default()
            }),
            Some(ShortcutSuppression::KeyboardGrab)
        );
        assert_eq!(
            select_shortcut_suppression(ShortcutContext {
                focused_surface_inhibited: true,
                exclusive_layer: true,
                ..ShortcutContext::default()
            }),
            Some(ShortcutSuppression::SurfaceInhibitor)
        );
    }

    #[test]
    fn test_vt_switch_direct_keysyms() {
        let empty_mods = ModifiersState::default();
        assert_eq!(vt_switch_target(XF86XK_SWITCH_VT_1, &empty_mods), Some(1));
        assert_eq!(vt_switch_target(XF86XK_SWITCH_VT_3, &empty_mods), Some(3));
        assert_eq!(vt_switch_target(XF86XK_SWITCH_VT_7, &empty_mods), Some(7));
        assert_eq!(vt_switch_target(XF86XK_SWITCH_VT_12, &empty_mods), Some(12));
    }

    #[test]
    fn test_vt_switch_ctrl_alt_function_keys() {
        let mods = ModifiersState {
            ctrl: true,
            alt: true,
            ..ModifiersState::default()
        };

        assert_eq!(vt_switch_target(XK_F1, &mods), Some(1));
        assert_eq!(vt_switch_target(XK_F2, &mods), Some(2));
        assert_eq!(vt_switch_target(XK_F3, &mods), Some(3));
        assert_eq!(vt_switch_target(XK_F7, &mods), Some(7));
        assert_eq!(vt_switch_target(XK_F12, &mods), Some(12));

        // Missing ctrl
        let no_ctrl = ModifiersState {
            alt: true,
            ..ModifiersState::default()
        };
        assert_eq!(vt_switch_target(XK_F3, &no_ctrl), None);

        // Missing alt
        let no_alt = ModifiersState {
            ctrl: true,
            ..ModifiersState::default()
        };
        assert_eq!(vt_switch_target(XK_F3, &no_alt), None);

        // Different key
        assert_eq!(vt_switch_target(XK_ESCAPE, &mods), None);
        assert_eq!(vt_switch_target(XK_A, &mods), None);
    }

    #[test]
    fn recovery_chord_is_exact_and_deliberate() {
        let chord = ModifiersState {
            logo: true,
            shift: true,
            ..ModifiersState::default()
        };
        assert!(is_shortcut_recovery_chord(XK_ESCAPE, &chord));
        assert!(!is_shortcut_recovery_chord(XK_Q, &chord));
        assert!(!is_shortcut_recovery_chord(
            XK_ESCAPE,
            &ModifiersState {
                logo: true,
                ..ModifiersState::default()
            }
        ));
        assert!(!is_shortcut_recovery_chord(
            XK_ESCAPE,
            &ModifiersState {
                ctrl: true,
                ..chord
            }
        ));
    }
}
