[colors.tag.normal]
inactive = { fg = "#DFDFDF", bg = "#121212", detail = "#121212" }
filled = { fg = "#DFDFDF", bg = "#384252", detail = "#89B3F7" }
focus = { fg = "#000000", bg = "#81c995", detail = "#1e8e3e" }
nofocus = { fg = "#000000", bg = "#fdd663", detail = "#f9ab00" }
empty = { fg = "#000000", bg = "#f28b82", detail = "#d93025" }

[colors.tag.hover]
inactive = { fg = "#DFDFDF", bg = "#1C1C1C", detail = "#121212" }
filled = { fg = "#DFDFDF", bg = "#4C5564", detail = "#a1c2f9" }
focus = { fg = "#000000", bg = "#99d3aa", detail = "#4ba465" }
nofocus = { fg = "#000000", bg = "#fddd82", detail = "#f9bb33" }
empty = { fg = "#000000", bg = "#f4a19a", detail = "#e05951" }

[colors.window.normal]
focus = { fg = "#DFDFDF", bg = "#384252", detail = "#89B3F7" }
normal = { fg = "#DFDFDF", bg = "#121212", detail = "#121212" }
minimized = { fg = "#384252", bg = "#121212", detail = "#121212" }
sticky = { fg = "#000000", bg = "#fdd663", detail = "#f9ab00" }
sticky_focus = { fg = "#000000", bg = "#81c995", detail = "#1e8e3e" }
overlay = { fg = "#000000", bg = "#fdd663", detail = "#f9ab00" }
overlay_focus = { fg = "#000000", bg = "#81c995", detail = "#1e8e3e" }

[colors.window.hover]
focus = { fg = "#DFDFDF", bg = "#4C5564", detail = "#a1c2f9" }
normal = { fg = "#DFDFDF", bg = "#1C1C1C", detail = "#1C1C1C" }
minimized = { fg = "#4C5564", bg = "#121212", detail = "#121212" }
sticky = { fg = "#000000", bg = "#fddd82", detail = "#f9bb33" }
sticky_focus = { fg = "#000000", bg = "#99d3aa", detail = "#4ba465" }
overlay = { fg = "#000000", bg = "#fddd82", detail = "#f9bb33" }
overlay_focus = { fg = "#000000", bg = "#99d3aa", detail = "#4ba465" }

[colors.close_button.normal]
normal = { fg = "#DFDFDF", bg = "#f28b82", detail = "#d93025" }
locked = { fg = "#DFDFDF", bg = "#fdd663", detail = "#f9ab00" }
fullscreen = { fg = "#DFDFDF", bg = "#f28b82", detail = "#d93025" }

[colors.close_button.hover]
normal = { fg = "#DFDFDF", bg = "#f4a19a", detail = "#e05951" }
locked = { fg = "#DFDFDF", bg = "#fddd82", detail = "#f9bb33" }
fullscreen = { fg = "#DFDFDF", bg = "#f4a19a", detail = "#e05951" }

[colors.border]
normal = "#384252"
tile_focus = "#89B3F7"
float_focus = "#81c995"
snap = "#fdd663"

[colors.status]
fg = "#DFDFDF"
bg = "#121212"
detail = "#121212"

# List of fonts to use for bar text, in order of preference/fallback
fonts = ["Inter-Regular:size=12", "Fira Code Nerd Font:size=12"]
