static const char *fonts[] = {"Cantarell-Regular:size=12", "Fira Code Nerd Font:size=12"};
static const char col_gray1[] = "#292f3a"; /* top bar d */
static const char col_gray2[] = "#ffffff";/*unfocused fonts d */
static const char col_gray3[] = "#747c90";/*unfocused border d */
static const char col_gray4[] = "#ffffff";/*focused fonts d */
static const char col_gray5[] = "#4dadd4";/*focused windows d */
static const char col_cyan[] = "#5294E2";/*focused instantmenu or topbar d */