use std::collections::{HashMap, HashSet};

use crate::contexts::WmCtx;
use crate::geometry::MoveResizeOptions;
use crate::layouts::LayoutOutput;
use crate::types::client::Client;
use crate::types::{Direction, Monitor, Point, Rect, Size, TagMask, WindowId};

pub const OVERVIEW_MODE_NAME: &str = "overview";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExitMode {
    RestorePrevious,
    ToSelectedWindow,
}

#[derive(Debug, Clone)]
pub struct OverviewState {
    restore_tags: TagMask,
    /// Stable bottom-to-top card order captured on entry. Focus changes update
    /// the normal model stack, but must not reshuffle or obscure overview cards.
    window_order: Vec<WindowId>,
    /// Geometry before overview first moved each window. `Client::float_geo`
    /// cannot serve as the undo log because logical overview moves update it.
    restore_geometry: HashMap<WindowId, Rect>,
    /// The card selected by the overview. Pointer hover may change this without
    /// sending keyboard input to the application; keyboard focus changes keep
    /// it in sync through [`follow_focus`]. Confirming overview commits this
    /// selection as the real focused window.
    active_window: Option<WindowId>,
    /// Crossing events can be generated by the cards themselves moving under
    /// a stationary pointer. Remembering the physical position prevents such
    /// events from feeding an animation back into itself.
    last_pointer_position: Option<Point>,
}

impl OverviewState {
    pub(crate) fn new(
        restore_tags: TagMask,
        window_order: Vec<WindowId>,
        restore_geometry: HashMap<WindowId, Rect>,
        active_window: Option<WindowId>,
    ) -> Self {
        Self {
            restore_tags,
            window_order,
            restore_geometry,
            active_window,
            last_pointer_position: None,
        }
    }

    fn update_pointer_target(
        &mut self,
        target: Option<WindowId>,
        pointer_position: Option<Point>,
    ) -> bool {
        if pointer_position.is_some() && self.last_pointer_position == pointer_position {
            return false;
        }
        if pointer_position.is_some() {
            self.last_pointer_position = pointer_position;
        }
        if target.is_none() || self.active_window == target {
            return false;
        }
        self.active_window = target;
        true
    }

    fn follow_focus(&mut self, focused: Option<WindowId>) -> bool {
        let focused = focused.filter(|win| self.window_order.contains(win));
        if focused.is_none() || self.active_window == focused {
            return false;
        }
        self.active_window = focused;
        true
    }

    fn reconcile_order(&mut self, ordered_windows: &[WindowId]) {
        self.window_order.clear();
        self.window_order.extend_from_slice(ordered_windows);
        if !self
            .active_window
            .is_some_and(|win| ordered_windows.contains(&win))
        {
            self.active_window = ordered_windows.first().copied();
        }
    }
}

pub(crate) fn handle_mode_transition(
    ctx: &mut WmCtx<'_>,
    previous_mode: &crate::core_state::ActiveWmMode,
    next_mode: &crate::core_state::ActiveWmMode,
    overview_exit: ExitMode,
) {
    match (previous_mode, next_mode) {
        (crate::core_state::ActiveWmMode::Overview, crate::core_state::ActiveWmMode::Overview) => {}
        (crate::core_state::ActiveWmMode::Overview, _) => exit(ctx, overview_exit),
        (_, crate::core_state::ActiveWmMode::Overview) => enter(ctx),
        _ => {}
    }
}

/// Exit overview mode with a specific [`ExitMode`].
///
pub fn exit_overview(ctx: &mut WmCtx<'_>, mode: ExitMode) {
    ctx.transition_current_mode(crate::core_state::ActiveWmMode::Default, mode);
}

fn enter(ctx: &mut WmCtx<'_>) {
    let selected_monitor_id = ctx.core().model().selected_monitor_id();
    let selected_window = ctx.core().model().selected_win();
    let all_tags = TagMask::all(ctx.core().model().tags.count());
    let window_order = {
        let model = ctx.core().model();
        let monitor = model.expect_selected_monitor();
        initial_window_order(monitor, &model.clients, all_tags)
    };
    let active_window = selected_window
        .filter(|win| window_order.contains(win))
        .or_else(|| window_order.first().copied());
    let restore_geometry = window_order
        .iter()
        .filter_map(|win| {
            ctx.core()
                .model()
                .client(*win)
                .map(|client| (*win, client.geo))
        })
        .collect();

    {
        let mon = ctx.core_mut().model_mut().expect_selected_monitor_mut();
        if mon.overview_state.is_some() {
            return;
        }
        let restore_tags = mon.selected_tags();
        // The all-tags view is a temporary projection, not user navigation.
        // Updating tag history here makes Super+Tab point back to the tag
        // overview will restore, producing a same-tag history entry on exit.
        mon.set_selected_tags(all_tags);
        mon.overview_state = Some(OverviewState::new(
            restore_tags,
            window_order,
            restore_geometry,
            active_window,
        ));
    }

    crate::focus::focus(ctx, active_window);
    ctx.core_mut()
        .queue_layout_for_monitor_urgent(selected_monitor_id);
}

fn exit(ctx: &mut WmCtx<'_>, mode: ExitMode) {
    let state = {
        let mon = ctx.core_mut().model_mut().expect_selected_monitor_mut();
        mon.overview_state.take()
    };

    let Some(state) = state else { return };

    let selected_monitor_id = ctx.core().model().selected_monitor_id();

    match mode {
        ExitMode::RestorePrevious => {
            let restore_mask = state.restore_tags;
            restore_window_geometry(ctx, selected_monitor_id, &state.restore_geometry);

            if !restore_mask.is_empty() {
                let mon = ctx.core_mut().model_mut().expect_selected_monitor_mut();
                restore_overview_tags(mon, restore_mask, restore_mask);
            }

            crate::focus::focus(ctx, None);
        }
        ExitMode::ToSelectedWindow => {
            // Pointer hover deliberately does not send keyboard focus to cards
            // while overview is open. Commit the overview-owned selection on
            // confirmation, falling back to ordinary focus only when the card
            // disappeared before the exit transition.
            let selected_window = state
                .active_window
                .filter(|win| {
                    ctx.core()
                        .model()
                        .client(*win)
                        .is_some_and(|client| client.monitor_id == selected_monitor_id)
                })
                .or_else(|| ctx.core().model().selected_win());
            let selected_tags = selected_window.and_then(|win| {
                ctx.core()
                    .state()
                    .model
                    .client(win)
                    .map(|c| c.tags.without_scratchpad())
                    .filter(|tags| !tags.is_empty())
            });
            let restore_mask = state.restore_tags;

            restore_window_geometry(ctx, selected_monitor_id, &state.restore_geometry);

            let target_mask = selected_tags.or(Some(restore_mask));
            if let Some(mask) = target_mask
                && !mask.is_empty()
            {
                let mon = ctx.core_mut().model_mut().expect_selected_monitor_mut();
                restore_overview_tags(mon, restore_mask, mask);
            }

            if let Some(win) = selected_window {
                crate::focus::focus(ctx, Some(win));
            } else {
                crate::focus::focus(ctx, None);
            }
        }
    }

    ctx.core_mut()
        .queue_layout_for_monitor_urgent(selected_monitor_id);
}

/// Leave overview's temporary all-tags projection without treating that
/// projection as tag history. When selection chooses another tag, replay the
/// transition from the pre-overview mask so ordinary Super+Tab semantics are
/// retained.
fn restore_overview_tags(monitor: &mut Monitor, restore_mask: TagMask, target_mask: TagMask) {
    monitor.set_selected_tags(restore_mask);
    if target_mask != restore_mask {
        let _ = monitor.set_selected_tags_with_history(target_mask);
    }
}

pub fn toggle_overview(ctx: &mut WmCtx<'_>, _mask: TagMask) {
    if ctx.core().model().is_overview_active() {
        exit_overview(ctx, ExitMode::ToSelectedWindow);
        return;
    }

    if ctx
        .core()
        .model()
        .expect_selected_monitor()
        .clients
        .is_empty()
    {
        return;
    }

    ctx.set_current_mode(crate::core_state::ActiveWmMode::Overview);
}

pub fn cancel_overview(ctx: &mut WmCtx<'_>, _mask: TagMask) {
    if !ctx.core().model().is_overview_active() {
        return;
    }

    ctx.reset_mode();
}

#[derive(Debug, Clone)]
pub(crate) struct OverviewLayout {
    pub moves: Vec<LayoutOutput>,
    /// Complete managed card order, bottom-to-top.
    pub z_order: Vec<WindowId>,
}

/// Update overview selection from physical pointer motion without sending
/// keyboard input to the hovered application. Returns `true` when overview
/// consumed the hover event. The selection becomes real focus when overview is
/// confirmed.
pub fn hover_window(
    ctx: &mut WmCtx<'_>,
    hovered_window: Option<WindowId>,
    pointer_position: Option<Point>,
) -> bool {
    if !ctx.core().model().is_overview_active() {
        return false;
    }

    let monitor_id = ctx.core().model().selected_monitor_id();
    let eligible = hovered_window.filter(|win| {
        let model = ctx.core().model();
        let monitor = model.expect_selected_monitor();
        model.client(*win).is_some_and(|client| {
            client.monitor_id == monitor_id && overview_eligible(client, monitor.selected_tags())
        })
    });

    let changed = {
        let monitor = ctx.core_mut().model_mut().expect_selected_monitor_mut();
        let Some(state) = monitor.overview_state.as_mut() else {
            return false;
        };
        state.update_pointer_target(eligible, pointer_position)
    };

    if changed {
        ctx.core_mut().queue_layout_for_monitor_urgent(monitor_id);
    }
    true
}

/// Keep overview emphasis aligned with an actual focus change. This is called
/// by the single shared focus entry point, so keyboard and IPC focus changes do
/// not need overview-specific branches at their individual call sites.
pub(crate) fn follow_focus(ctx: &mut WmCtx<'_>) {
    if !ctx.core().model().is_overview_active() {
        return;
    }
    let monitor_id = ctx.core().model().selected_monitor_id();
    let selected = ctx.core().model().selected_win();
    let changed = {
        let monitor = ctx.core_mut().model_mut().expect_selected_monitor_mut();
        let Some(state) = monitor.overview_state.as_mut() else {
            return;
        };
        state.follow_focus(selected)
    };
    if changed {
        ctx.core_mut().queue_layout_for_monitor_urgent(monitor_id);
    }
}

/// Move keyboard focus through the stable two-dimensional overview grid.
pub fn focus_direction(ctx: &mut WmCtx<'_>, direction: Direction) -> bool {
    let target = {
        let model = ctx.core().model();
        let monitor = model.expect_selected_monitor();
        let Some(state) = monitor.overview_state.as_ref() else {
            return false;
        };
        let windows = eligible_order(monitor, &model.clients, &state.window_order);
        grid_neighbor(
            &windows,
            state.active_window.or(monitor.selected),
            direction,
            monitor.work_rect(),
        )
    };
    let Some(target) = target else {
        return false;
    };
    crate::focus::focus(ctx, Some(target));
    true
}

/// Arrange visible windows as an overlapping card hand. Client sizes are
/// preserved: only their origins change. Because origins advance monotonically
/// in the same direction as z-order, every card retains an exposed, clickable
/// strip even when later cards overlap it.
pub fn compute(monitor: &mut Monitor, clients: &HashMap<WindowId, Client>) -> OverviewLayout {
    let selected_tags = monitor.selected_tags();
    let newly_visible = monitor
        .clients
        .iter()
        .copied()
        .filter_map(|win| {
            let client = clients.get(&win)?;
            overview_eligible(client, selected_tags).then_some((win, client.geo))
        })
        .collect::<Vec<_>>();
    if let Some(state) = monitor.overview_state.as_mut() {
        for (win, rect) in newly_visible {
            state.restore_geometry.entry(win).or_insert(rect);
        }
    }
    let mut ordered_windows = monitor
        .overview_state
        .as_ref()
        .map(|state| state.window_order.clone())
        .unwrap_or_default();
    ordered_windows.retain(|win| {
        clients
            .get(win)
            .is_some_and(|client| overview_eligible(client, selected_tags))
    });
    // Windows mapped during overview join at the top of the hand without
    // disturbing the positions of existing cards.
    for &win in &monitor.clients {
        if !ordered_windows.contains(&win)
            && clients
                .get(&win)
                .is_some_and(|client| overview_eligible(client, selected_tags))
        {
            ordered_windows.push(win);
        }
    }
    if let Some(state) = monitor.overview_state.as_mut() {
        state.reconcile_order(&ordered_windows);
    }

    let client_info: Vec<(WindowId, Size)> = ordered_windows
        .iter()
        .copied()
        .filter_map(|win| {
            let c = clients.get(&win)?;
            Some((win, Size::new(c.geo.w.max(1), c.geo.h.max(1))))
        })
        .collect();

    if client_info.is_empty() {
        return OverviewLayout {
            moves: Vec::new(),
            z_order: Vec::new(),
        };
    }

    let work_rect = monitor.work_rect();
    let sizes = client_info
        .iter()
        .map(|(_, size)| *size)
        .collect::<Vec<_>>();
    let active_index = monitor
        .overview_state
        .as_ref()
        .and_then(|state| state.active_window)
        .and_then(|win| {
            ordered_windows
                .iter()
                .position(|candidate| *candidate == win)
        })
        .unwrap_or(0);
    let rects = card_field_rects(work_rect, &sizes, active_index);
    let frame_count = if client_info.len() > crate::constants::animation::FAST_ANIM_THRESHOLD {
        crate::constants::animation::FAST_FRAME_COUNT
    } else {
        crate::constants::animation::DEFAULT_FRAME_COUNT
    };
    let moves = client_info
        .iter()
        .zip(rects)
        .map(|(&(win, _), rect)| LayoutOutput {
            win,
            rect,
            options: MoveResizeOptions::animate_to(frame_count),
        })
        .collect();

    // Include non-card managed windows below the hand. This matters on X11,
    // where sibling-based restacking otherwise leaves an excluded overlay at
    // an unspecified level which could cover the cards.
    let card_windows = ordered_windows.iter().copied().collect::<HashSet<_>>();
    let mut z_order = monitor
        .clients
        .iter()
        .copied()
        .filter(|win| clients.contains_key(win) && !card_windows.contains(win))
        .collect::<Vec<_>>();
    z_order.extend(ordered_windows);

    OverviewLayout { moves, z_order }
}

fn restore_window_geometry(
    ctx: &mut WmCtx<'_>,
    monitor_id: crate::types::MonitorId,
    geometry: &HashMap<WindowId, Rect>,
) {
    for (&win, &rect) in geometry {
        if ctx
            .core()
            .model()
            .client(win)
            .is_some_and(|client| client.monitor_id == monitor_id)
        {
            ctx.move_resize(win, rect, MoveResizeOptions::immediate());
        }
    }
}

fn overview_eligible(client: &Client, selected_tags: TagMask) -> bool {
    client.is_visible(selected_tags) && !client.is_edge_scratchpad()
}

fn initial_window_order(
    monitor: &Monitor,
    clients: &HashMap<WindowId, Client>,
    selected_tags: TagMask,
) -> Vec<WindowId> {
    let mut windows = monitor
        .clients
        .iter()
        .copied()
        .enumerate()
        .filter_map(|(index, win)| {
            let client = clients.get(&win)?;
            overview_eligible(client, selected_tags).then_some((
                client
                    .tags
                    .without_scratchpad()
                    .first_tag()
                    .unwrap_or(usize::MAX),
                index,
                win,
            ))
        })
        .collect::<Vec<_>>();
    windows.sort_by_key(|&(tag, index, _)| (tag, index));
    windows.into_iter().map(|(_, _, win)| win).collect()
}

fn eligible_order(
    monitor: &Monitor,
    clients: &HashMap<WindowId, Client>,
    preferred_order: &[WindowId],
) -> Vec<WindowId> {
    preferred_order
        .iter()
        .copied()
        .filter(|win| {
            clients
                .get(win)
                .is_some_and(|client| overview_eligible(client, monitor.selected_tags()))
        })
        .collect()
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct CardGrid {
    columns: usize,
    rows: usize,
}

impl CardGrid {
    fn for_work_rect(work_rect: Rect, card_count: usize) -> Self {
        if card_count == 0 {
            return Self {
                columns: 0,
                rows: 0,
            };
        }
        let aspect = f64::from(work_rect.w.max(1)) / f64::from(work_rect.h.max(1));
        let columns = ((card_count as f64 * aspect).sqrt().round() as usize).clamp(1, card_count);
        Self {
            columns,
            rows: card_count.div_ceil(columns),
        }
    }

    fn position(self, index: usize) -> (usize, usize) {
        (index / self.columns, index % self.columns)
    }
}

fn grid_neighbor(
    windows: &[WindowId],
    active: Option<WindowId>,
    direction: Direction,
    work_rect: Rect,
) -> Option<WindowId> {
    if windows.len() < 2 {
        return None;
    }
    // Navigation uses the same stable row-major topology as presentation. A
    // sparse final row clamps vertical motion to its nearest available card.
    let grid = CardGrid::for_work_rect(work_rect, windows.len());
    let index = active
        .and_then(|win| windows.iter().position(|candidate| *candidate == win))
        .unwrap_or(0);
    let (row, column) = grid.position(index);
    let target_index = match direction {
        Direction::Left => index.checked_sub(1).filter(|_| column > 0),
        Direction::Right => {
            (column + 1 < grid.columns && index + 1 < windows.len()).then_some(index + 1)
        }
        Direction::Up => row
            .checked_sub(1)
            .map(|target_row| target_row * grid.columns + column.min(grid.columns - 1)),
        Direction::Down => {
            let target_row = row + 1;
            if target_row >= grid.rows {
                None
            } else {
                let first = target_row * grid.columns;
                let last = (first + grid.columns).min(windows.len()) - 1;
                Some((first + column).min(last))
            }
        }
    };
    target_index.and_then(|target| windows.get(target).copied())
}

/// Lay out unscaled client cards on a two-dimensional, slightly staggered
/// field. Row and column territory expands around the active card and decays
/// smoothly with grid distance. Origins remain monotonic in row-major z-order,
/// which guarantees every covered card an exposed pointer target.
fn card_field_rects(work_rect: Rect, sizes: &[Size], active_index: usize) -> Vec<Rect> {
    if sizes.is_empty() {
        return Vec::new();
    }
    let grid = CardGrid::for_work_rect(work_rect, sizes.len());
    let (active_row, active_column) = grid.position(active_index.min(sizes.len() - 1));
    let column_edges = weighted_edges(work_rect.x, work_rect.w, grid.columns, active_column);
    let row_edges = weighted_edges(work_rect.y, work_rect.h, grid.rows, active_row);

    sizes
        .iter()
        .enumerate()
        .map(|(index, &size)| {
            let (row, column) = grid.position(index);
            let cell_left = column_edges[column];
            let cell_right = column_edges[column + 1];
            let cell_top = row_edges[row];
            let cell_bottom = row_edges[row + 1];
            // Alternating rows evoke a fish-scale field and expose content on
            // both axes. The offset is bounded so every origin stays on-screen.
            let stagger = if row % 2 == 1 {
                ((cell_right - cell_left) / 5).max(1)
            } else {
                0
            };
            let x = (cell_left + stagger).min(work_rect.right() - 1);
            let y = cell_top;
            let x = if size.w < cell_right - x {
                x + (cell_right - x - size.w) / 2
            } else {
                x
            };
            let y = if size.h < cell_bottom - cell_top {
                y + (cell_bottom - cell_top - size.h) / 2
            } else {
                y
            };
            Rect::new(x, y, size.w, size.h)
        })
        .collect()
}

fn weighted_edges(start: i32, extent: i32, count: usize, active: usize) -> Vec<i32> {
    debug_assert!(count > 0);
    let weights = (0..count)
        .map(|index| {
            let distance = index.abs_diff(active) as f64;
            1.0 + 4.0 / (distance + 1.0)
        })
        .collect::<Vec<_>>();
    let total = weights.iter().sum::<f64>();
    let mut edges = Vec::with_capacity(count + 1);
    edges.push(start);
    let mut cumulative = 0.0;
    for weight in weights {
        cumulative += weight;
        let offset = (f64::from(extent.max(1)) * cumulative / total).round() as i32;
        edges.push(start.saturating_add(offset));
    }
    if let Some(last) = edges.last_mut() {
        *last = start.saturating_add(extent.max(1));
    }
    // Extremely dense overviews retain distinct origins whenever the physical
    // pixel extent permits it.
    if extent.max(1) as usize >= count {
        let end = start.saturating_add(extent.max(1));
        for index in 1..count {
            let latest = end.saturating_sub((count - index) as i32);
            edges[index] = edges[index]
                .max(edges[index - 1].saturating_add(1))
                .min(latest);
        }
    }
    edges
}

#[cfg(test)]
#[path = "overview/tests.rs"]
mod tests;
